version: "3.9"

volumes:
  postgres_data: {}

services:
  packform-test:
    restart: always
    image: packform-test
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3000:3000
    environment:
      DB_PORT: ${DB_PORTL-5432}
      DB_HOST: ${DB_HOST:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-packform}
      SECRET: 7B4XAV8XOZ9BT52O
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - ./import_csv:/production/import_csv
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-packform}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
